language: node_js
node_js:
    - "0.8"
    - "0.10"

before_install:
    - sudo apt-get update

install:
    - sudo apt-get install imagemagick graphicsmagick
    - npm install -g grunt-cli
    - npm install

script: 'grunt travis'
